export enum MaterialType {
  ZIRCONIA = 'ZIRCONIA',
  PORCELAIN = 'PORCELAIN',
  METAL_CERAMIC = 'METAL_CERAMIC',
  ACRYLIC = 'ACRYLIC',
  COMPOSITE = 'COMPOSITE',
  TITANIUM = 'TITANIUM',
  GOLD = 'GOLD',
  OTHER = 'OTHER',
}
