export enum WorkType {
  CROWN = 'CROWN',
  BRIDGE = 'BRIDGE',
  DENTURE = 'DENTURE',
  IMPLANT = 'IMPLANT',
  VENEER = 'VENEER',
  INLAY_ONLAY = 'INLAY_ONLAY',
  ORTHODONTICS = 'ORTHODONTICS',
  OTHER = 'OTHER',
}
